import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Download, RefreshCw, BookOpen } from 'lucide-react';

interface ResultDisplayProps {
  content: string;
  sources?: string[];
  onReset: () => void;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ content, sources, onReset }) => {
  
  const handleDownload = () => {
    // Create a complete HTML document for download
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="zh-CN">
      <head>
        <meta charset="UTF-8">
        <title>OranjeStudie 学习资料</title>
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
          h1 { color: #ea580c; border-bottom: 2px solid #ea580c; padding-bottom: 10px; }
          h2 { color: #c2410c; margin-top: 30px; background-color: #fff7ed; padding: 10px; border-left: 5px solid #ea580c; }
          p { margin-bottom: 15px; }
          blockquote { border-left: 4px solid #fdba74; padding-left: 15px; color: #555; font-style: italic; margin: 15px 0; background-color: #fdfbf7; padding: 10px; }
          strong { color: #ea580c; background-color: #ffedd5; padding: 0 4px; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #fce7f3; }
        </style>
      </head>
      <body>
        ${document.getElementById('markdown-content')?.innerHTML || ''}
        <div style="margin-top: 50px; font-size: 12px; color: #888; text-align: center;">
            Generated by OranjeStudie AI
        </div>
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `OranjeStudie_Dutch_Material_${new Date().toISOString().slice(0, 10)}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-8 animate-fade-in-up">
      <div className="bg-white rounded-2xl shadow-xl border border-orange-100 overflow-hidden">
        {/* Header */}
        <div className="bg-orange-50 px-6 py-4 border-b border-orange-100 flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-2 text-orange-800">
                <BookOpen size={24} />
                <h2 className="text-xl font-bold">学习资料生成完毕</h2>
            </div>
            <div className="flex gap-3">
                <button 
                    onClick={onReset}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-orange-700 bg-white border border-orange-200 rounded-lg hover:bg-orange-50 transition-colors"
                >
                    <RefreshCw size={16} />
                    新对话
                </button>
                <button 
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-orange-600 rounded-lg hover:bg-orange-700 shadow-sm transition-colors"
                >
                    <Download size={16} />
                    下载文档
                </button>
            </div>
        </div>

        {/* Content */}
        <div className="p-8 md:p-12">
            <div id="markdown-content" className="markdown-body">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {content}
                </ReactMarkdown>
            </div>

            {/* Sources Footnote */}
            {sources && sources.length > 0 && (
                <div className="mt-8 pt-6 border-t border-slate-100">
                    <h4 className="text-sm font-semibold text-slate-500 mb-2">参考来源:</h4>
                    <ul className="text-xs text-slate-400 space-y-1">
                        {sources.map((source, idx) => (
                            <li key={idx} className="truncate">
                                <a href={source} target="_blank" rel="noopener noreferrer" className="hover:text-orange-500 hover:underline">
                                    {source}
                                </a>
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default ResultDisplay;